---
- name: Set kubelet address
  lineinfile:
    dest: /etc/kubernetes/kubelet
    regexp: '^KUBELET_ADDRESS='
    line: 'KUBELET_ADDRESS="--address=0.0.0.0"'

- name: Set kubelet hostname
  lineinfile:
    dest: /etc/kubernetes/kubelet
    regexp: '^KUBELET_HOSTNAME='
    line: 'KUBELET_HOSTNAME="--hostname-override={{ ansible_hostname }}"'

- name: Set kubelet API server
  lineinfile:
    dest: /etc/kubernetes/kubelet
    regexp: '^KUBELET_API_SERVER='
    line: 'KUBELET_API_SERVER="--api-servers=http://master:8080"'

- name: Start node services
  systemd: name={{ item }} state=restarted enabled=True
  with_items:
    - kube-proxy
    - kubelet
    - flanneld
    - docker
