---
- name: Install Kubernetes Packages
  yum: name={{ item }} state=present
  with_items:
    - docker
    - kubernetes
    - etcd
    - flannel
    
- name: Disable SELinux
  selinux:
    state: disabled
    
- name: Disable firewalld
  systemd: name=firewalld enabled=no state=stopped
